src/gen_module.sh, tests/run_tests.sh
Be able to re-run the script locally without errors
=> Fix: make mkdirs idempotent

tests/python/run_tests.py
Fixing wrong `arg` variable
Fix error inside the exception
=> Fix: Typo in run_tests.py

tests/run_tests.sh
Do not claim tests to be successful if there are invalid / unreadable files in the "raw_modules" folder. 
This allows running tests in the CI which actually fail in case the artifacts generated are invalid.
=> Fix: Hidden silent errors in tests

tests/run_tests.sh
Do not hardcode version "[0-9]{8}", but also allow all kinds of PEP 440 versions.
Replacing hardcoded string with generic PEP 440 check.
Depends on #43
=> Add: PEP440 check to generated modules

.gitignore
Have less false-positives on `git status` after building the package:
* virtualenv path
* temporary build files
* artifact folders
Adds temporary build artifacts to gitignore
I also added `.venv` which is created by python's virtualenv
=> Update: add script build files to gitignore

.github/workflows/fake-bpy-module-ci.yml
Enable Actions on PRs and pushes to master branch
=> Add: Run Github Actions on PRs and master branch

.github/workflows/fake-bpy-module-ci.yml
This makes the build fully parallel and hence speeds up the build drastically.
Making use of [matrix strategy for Github Actions](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix)
This depends on #54
=> Use Github Actions Matrix feature

tools/pip_package/build_pip_package.sh, tools/utils/download_blender.sh
Upgrade to Blender 2.83.x to v2.83.1
Fixes #59
=> Update: Updade Blender 2.83 to 2.83.1

.github/workflows/fake-bpy-module-ci.yml, tests/pylint_cycles.sh
This PR is a quick&dirty CI solution to show the intent of the work which triggers #48
It adds a script which tries to lint the cycles addon in Blender together fake-bpy-modules.
Just check the failure of the CI to see which errors are remaining for each version of Blender.
=> [RFC] Add test for cycles addon

src/fake_bpy_module/analyzer.py, src/fake_bpy_module/generator.py
Code cleanup:
W0614: Unused import
=> Fix: Remove unsued imports

src/fake_bpy_module/generator.py
W0612: Unused variable 'e' (unused-variable)
=> Change: remove unused variable 'e'

.github/workflows/fake-bpy-module-ci.yml
Make the CI usuable again
Using new GITHUB_ENV syntax
**Additional comments** [Optional]
=> Replace set-env to fix CVE-2020-15228

src/gen_module.sh, tests/pylint_cycles.sh, tools/pip_package/build_pip_package.sh, tools/utils/download_blender.sh
Use release version of Blender 2.91.0
Bump version and use official upstream download
**Additional comments** [Optional]
=> Update: Update to Blender 2.91.0

docs/setup_pycharm.md
*The purpose of the pull request. (e.g. Fix Bug, Feature request)*
Enhance documentation  on line 17
*The description about this pull request.*
Typos fixed
No break on code. Just clear and enhanced documentation
=> Menu denomination fixed (line 17)

README.md
*The purpose of the pull request. (e.g. Fix Bug, Feature request)*
Enhance documentation  on lines 05, 12
*The description about this pull request.*
Typos fixed
No break on code. Just clear and enhanced documentation
=> Minor fixes (lines 05, 12)

docs/setup_visual_studio_code.md
*The purpose of the pull request. (e.g. Fix Bug, Feature request)*
*The description about this pull request.*
**Additional comments** [Optional]
=> added steps to Setup IDE: Visual Studio Code

src/fake_bpy_module/generator.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/base_generator_test_generate.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/base_generator_test_generate.pyi, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/base_generator_test_generate_custom_modifier.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/base_generator_test_generate_custom_modifier.pyi, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/package_generator_test_exceptional_rule/module_exceptional/__init__.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/package_generator_test_multiple_rules/module_1/__init__.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/package_generator_test_multiple_rules/module_1/submodule_1/__init__.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/package_generator_test_multiple_rules/module_2/__init__.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/package_generator_test_single_rule/module_abc/__init__.py
=> Fix: Remove sys from .pyi files

.gitignore, src/fake_bpy_module/common.py
=> Fix: Sort data types in unions

src/fake_bpy_module/generator.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/base_generator_test_generate.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/base_generator_test_generate.pyi, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/base_generator_test_generate_custom_modifier.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/base_generator_test_generate_custom_modifier.pyi
=> Fix: Sort imports

src/mods/common/analyzer/append/bmesh.types.mod.rst
Add slice support for `BMElemSeq`, `BMVertSeq`, `BMEdgeSeq`, and `BMFaceSeq`.
- Similar to #241 
- Replaces #263
=> Update: Support slice for BMElemSeq, BMVertSeq, BMEdgeSeq, BMFaceSeq

src/gen.py
=> Fix: gen.py typing issue

src/mods/common/analyzer/append/mathutils.mod.rst
=> Fix: mathutils classes to support slice assignment of themselves #336

src/fake_bpy_module/generator/writers.py, src/mods/common/analyzer/append/bpy.types.mod.rst, src/mods/common/analyzer/update/bpy.types.mod.rst
- Follow up to #332 adding the same mods to it as `bpy_prop_collection`.
The mods adds iterable/sequence methods.
Copy exactly the `bpy_prop_collection` mods for the `bpy_prop_collection_idprop` ones.
=> Add bpy_prop_collection_idprop mods

.gitignore, tests/run_pre_tests.sh, tests/run_tests.sh
Small fixes, just the papercuts I've met working with the repository.
=> Add more error handling to repository scripts
