src/gen.py
Fix for error on Windows: UnicodeEncodeError: 'charmap' codec can't encode character '\u2190'
=> Fix: UnicodeEncodeError: 'charmap' codec can't encode character on Windows

src/gen_module.sh, tests/run_tests.sh, tools/pip_package/build_pip_package.sh
[The first commit](https://github.com/nutti/fake-bpy-module/commit/0ff9cad9690688ca753f2df9c80b139cbdb1636e) adds python checks to the shell scripts so you don't run weird behaviour.
~[The second commit](https://github.com/nutti/fake-bpy-module/commit/804acaa518741a0906c3c52f11c3d16d12a687b5) increases the python version to 3.7, as apparently your code is not compatible with python3.6.9:~
https://github.com/nutti/fake-bpy-module/blob/a08ae2ecf74c29fef8b4d64bdfb55acec4518820/src/gen.py#L10
EDIT: Second commit does not seem to be needed with the `typing` python module on python 3.6.
=> Fix Python requirement

tools/pip_package/build_pip_package.sh
Abort early if the RELEASE_VERSION is invalid. Otherwise you have to wait for the full build and then run into an error very late.
Uses the PEP440 check from setuptools.
=> Add: check if RELEASE_VERSION is PEP440 compatible

tools/utils/download_blender.sh
Make it compatible with tests like `set -e`
Currently, the changed line is always returning `false` and together with `set -e` will cause the script to fail.
=> Fix: unintentional failed command during download

src/gen_module.sh, tests/run_tests.sh, tools/pip_package/build_pip_package.sh, tools/pip_package/publish_to_pypi.sh, tools/utils/download_blender.sh
Making scripts end early if an error occurs, and do not continue silently.
Using bash built ins to help in the process.
Also using `/usr/bin/env bash` in the shebang to be compatible with other Linux distro (e.g. [NixOS](https://nixos.org/)).
=> Fix: replace bash with env bash and use errexit

.github/workflows/fake-bpy-module-ci.yml, src/gen_module.sh
Speeds up tag switching tremendously
**Description about the pull request** 
Instead of fetching the full master, fetching a tag and then switching, just shallow fetch the tag directly and switch.
Speeds up the fetching during building from 2min to 15 seconds for me.
Also, rename `branch_name` to `tag_name` as no branches are being used here.
I tested the commit with my current Github Actions. As far as I can tell, this should not interfere anywhere.
=> Fix: gen_module only fetch tag ref

.circleci/config.yml, .github/workflows/fake-bpy-module-ci.yml, tools/utils/download_blender.sh
Create a consistent naming syntax. Currently, the `2.xx` syntax is used in some scripts, while `v2xx` is used in others. Trying to make them easily convertible (by adding/stripping `v` at the start)
Replace array addressing with `v2xx` syntax, making the download directories not use the `v2xx` syntax.
Additionally, cleaning up the `build_pip_package.sh` script internally to purge the old syntax. These two commits can be split up in different PRs if you prefer.
The consistent naming in the download folders is required to make the CI job easily run in parallel on Github Actions. Without it, it will cause a lot of (unnecessary) additional code.
=> Remove v2xx syntax in downloads

tools/pip_package/build_pip_package.sh
Assuming #54 is accepted, this PR makes the code consistent across scripts.
Replace the "v2xx" syntax with "v2.xx".
Independent of #54
=> Remove v2xx syntax in pip

.github/workflows/fake-bpy-module-ci.yml
Create and store all build artifacts for automatic building and hence easy testing.
See artifacts for current PR: https://github.com/nutti/fake-bpy-module/actions/runs/148697983
In this PR, we are creating artifacts for the "raw_modules" folder and the generated pip packages.
The pip artifact allows you to manually download and install on your local machine with the `pip install <filename>` command.
I chose a second-exact resolution timestamp for the files, as we might have multiple builds per day. While all those artifact filenames have a timestamp as a version, I did not (as requested) modify the RELEASE_VERSION.
EDIT: I removed all independent parts of this PR and focus …
=> Create and archive build artifacts

tools/utils/download_blender.sh
The current download script gives a lot of spam-like output when run in parallel (i.e. with download `all`), so I decided to improve the script a bit.
* Replace cd with pushd/popd
* Fail on HTTP error with curl
* Silence curl output as it breaks with multiple processes
* Make script idempotent by removing files before moving files around
* Avoid removal of root "/" folders by checking $output_dir early
I tried to make the code I created/modified conform to [shellcheck](https://github.com/koalaman/shellcheck).
=> Update: Improve Blender download script

.gitignore, tools/utils/download_blender.sh
This avoids re-downloading Blender binary files when building pip  packages locally.
Download files to a "downloads/" folder and keep binaries there.
On each download attempt verify the integrity existing downloads and in case of a failure, re-download them.
This depends on #62
=> Verify Blender downloads and keep them

.github/workflows/fake-bpy-module-ci.yml
Make the PyPi publishing process automatic without manual user intervention.
1. It adds a new trigger for Github releases.
1. It changes versioning scheme 
1. default: `YYYYmmdd.devHHMMSS`
2. releases: infer version from tag name
3. PRs: use default + githash: `YYYYmmdd.devHHMMSS+abcdef01`
1. Automatically builds + publishes all non-PRs to TestPyPi
1. Automatically builds + publishes all GitHub releases to PyPi
**Additional comments**
Do you want me to split the PR into two separate ones? 
1. For changing the versioning scheme
1. For adding the PyPi publishing
**Release workflow**
In order to publish automatically to PyPi, you have to [go into releases](https://github.com/nutti/fake-bpy-module/releases) and create …
=> auto PyPi publishing

src/fake_bpy_module/common.py
W1401: Anomalous backslash in string: '\.'. String constant might be
missing an r prefix. (anomalous-backslash-in-string)
=> Fix: Make "\." a raw string

src/fake_bpy_module/analyzer.py
Trying to make code easier readable
R1714: Consider merging these comparisons with "in" to "c in ('(', '{', '[')" (consider-using-in)
=> Change: replace a == x to a in (x)

tools/utils/download_blender.sh
`curl` should not fail in case the download path is a redirect (HTTP 3xx).
Simply follow redirects
=> Fix: Make curl follow redirects

docs/generate_modules.md, src/gen_module.sh
To let the CI runs not ignore Python exceptions
This will show currently silent errors and abort scripts if there has
been a Python exception raised somewhere in Blender.
Suggested when reporting https://developer.blender.org/T82494
=> Change: Add --python-exit-code to blender calls

src/fake_bpy_module/generator.py
Empty docstring does not seem to add any value.
Removing them allows having a cleaner file at the end.
With Ruff formatting, the generated code is more compact.
In some cases, empty docstrings were not generated.
Now, in all cases, empty docstrings are not generated.
=> Update: Remove empty docstring in generated code

src/fake_bpy_module/generator.py
- Described in #167.
Only generate `py.typed` files at top-level (`module_level` = 0).
=> Update: Remove sub-package py.typed

tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/base_generator_test_dump_json.json, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/base_generator_test_generate.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/base_generator_test_generate.pyi
The missing default argument of `param_2` caused a syntax error
The default argument of `param_2` was specified in `parameter_details` but not in `parameters`.
The different test and fixtures have been updated accordingly.
=> Fix: Add missing default argument in code generation tests

docs/generate_modules.md, docs/github_actions_tests.md, src/gen_module.sh, tools/gen_module/Dockerfile, tools/gen_module/run_gen_module.sh, tools/gen_module/run_gen_module_in_docker.sh, tools/github_actions_tests/run_github_actions_tests.sh
* Allow easy module generation for any Blender version
* Shortcut time-consuming build processes by comparing file timestamps
* Add `run_gen_module.sh` to easily run `gen_module.sh` in docker
```bash
$ bash tools/utils/run_gen_module.sh
Usage: bash tools/utils/run_gen_module.sh <target_version>
Available <target_version>: 2.78 2.79 2.80 2.81 2.82 2.83 2.90 2.91 2.92 2.93 3.0 3.1 3.2 3.3 3.4 3.5 3.6 4.0 latest
$ bash tools/utils/run_gen_module.sh 4.0
... build log ...
```
The results are output to `build` directory.
```bash
$ ls build
blender-bin  blender-src  examples  generated_mods  results  sphinx-in  sphinx-in-tmp
```
| Directory | Contents |
|----|----|
| `build/blender-bin` | Blender binaries |
| `build/blender-src` | Blender source code |
| `build/examples` | Blender Python API …
=> Add gen modules scripts

src/fake_bpy_module/analyzer.py, src/fake_bpy_module/common.py, src/fake_bpy_module/generator.py
* Reduce the execution time of `gen.py`.
* I profiled `gen.py` and found that compiling the regular expressions takes a long time.
[profile_before.txt](https://github.com/nutti/fake-bpy-module/files/13893891/profile_before.txt)
`817374612 function calls (815148474 primitive calls) in 308.347 seconds`
* Pre-compiling the regular expressions makes it 3.7 times faster.
[profile_after.txt](https://github.com/nutti/fake-bpy-module/files/13893889/profile_after.txt)
`126576412 function calls (126367374 primitive calls) in 82.795 seconds`
* Output results changed slightly. The change has not yet been checked.
[results_diff.txt](https://github.com/nutti/fake-bpy-module/files/13893944/results_diff.txt)
```
diff -ur build/results_original build/results > results_diff.txt
```
=> Pre-compile regular expressions for speed

docs/generate_modules.md, tools/docker/Dockerfile
0bc095e7a6cecd3df905a61a4b4fcfed53c77696 moved `requirements.txt` to `src/requirements.txt` but left some references to the old location, particularly in the documentation, which this pull request fixes.
=> Fix references to old requirements.txt location

docs/generate_modules.md
c6338daa0b4b7464c39fc1ed1a9619d8f1e1bca1 added `target` parameters to a number of scripts, but the build documentation was not updated to match.
I have not touched the docker section.
=> Fix missing 'target' parameters in build docs

docs/generate_modules.md
I missed a second occurrence of `gen_module.sh` in 30152a68f8f795a681074d2af317d39c0d9612fb.
dc761c8e024dd61f03425ae79798eb6e425a2c6a missed a second occurrence of cloning `blender.git`.
=> Fix incomplete fixes to build docs

.gitignore
In the case that `gen_module.sh` fails for some reason (e.g. #185) `src/gen_module-tmp` and `src/mods/generated_mods` are not removed, however only the latter was being ignored by git.
=> Ignore src/gen_module-tmp

docs/generate_modules.md, tools/gen_module/Dockerfile
Due to the update of the Python version from 3.8 to 3.9 in GitHub Actions dependencies in commit 782a482d4eb5e48ab932cc0e3d60fcbbcb435a72, we need to update the Python version locally to align with the GitHub Actions environment.
- Update the Python version in `tools/gen_module/Dockerfile` from 3.8 to 3.9.
- Correct the incorrect script file name in `docs/generate_modules.md`.
=> Update Python Version for local gen_module

src/fake_bpy_module/generator/generator.py
- Fix #167
Count the number of `/` to determine if the module level to only generate `py.typed` files at the root of packages.
=> Fix: generate only needed py.typed

src/fake_bpy_module/analyzer/directives.py
- Fix #210
- Fix #209 
To solve the issues above, I manually convert to string `set` but also `list`, `tuple`, and `dict` as they could have the same problem of extra quotes.
=> Fix: remove extra quotes from set default value

src/fake_bpy_module/generator/writers.py, src/fake_bpy_module/transformer/bpy_ops_override_parameters_adder.py, src/fake_bpy_module/transformer/data_type_refiner.py, src/fake_bpy_module/transformer/default_value_filler.py, src/mods/common/analyzer/append/bpy.types.mod.rst, src/mods/common/analyzer/new/bpy.types.mod.rst, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/json_writer_test/expect/class/class.json, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/json_writer_test/expect/class/class.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/json_writer_test/input/class/class.rst, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_code_writer_test/expect/class/class.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_code_writer_test/expect/class/class.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_code_writer_test/expect/function/function.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_code_writer_test/input/class/class.rst, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_interface_writer_test/expect/class/class.pyi, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_interface_writer_test/expect/class/class.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_interface_writer_test/expect/function/function.pyi, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_interface_writer_test/input/class/class.rst, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/bpy_ops_override_parameters_adder_test/expect/basic_transformed.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/special_data_type_transformed.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/various_data_type_transformed.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/default_value_filler_test/expect/basic.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/default_value_filler_test/expect/basic_transformed.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/default_value_filler_test/input/basic.rst
This pull-request modernize the syntax used in the generated pyi files.
=> Use modern Python 3.10 syntax

src/fake_bpy_module/transformer/data_type_refiner.py
- Fix #211
- Fix #212 
Sometimes the description have an additional comma that was not taken into account in the regexes.
=> Fix: enum regexes to refine data types

src/fake_bpy_module/transformer/data_type_refiner.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/various_data_type_transformed.xml
=> Fix: use str only for enum types instead of str|int

docs/generate_modules.md
The documentation had not been updated to reflect the renaming of the `master` branch in the Blender git repository to `main`.
=> Fix build docs: Blender master branch now called main

src/mods/common/analyzer/update/bpy.app.mod.rst
327a3c4eb313c7b2a9ae35f8dce762e81c3f9a67 reintroduced `typing.Tuple` syntax into a mod file, a regression on #161.
https://github.com/nutti/fake-bpy-module/blob/327a3c4eb313c7b2a9ae35f8dce762e81c3f9a67/src/mods/common/analyzer/update/bpy.app.mod.rst?plain=1#L7
This PR has no conflicts with #221.
=> Fix typing.Tuple syntax reintroduced in mod file

src/fake_bpy_module/generator/writers.py
- Fix regression of #161 with `typing.Optional`.
=> Fix: Use | None instead of typing.Optional

src/mods/common/analyzer/update/bpy.types.mod.rst
`bpy_prop_collection.items()`'s return type was being refined away due to a typo in e0e70e19630a511340dd298e24b30a1ea67e435d.
=> Fix bpy_prop_collection.items missing return type

src/mods/common/analyzer/new/bpy.types.mod.rst
Removes incorrect `bpy_prop_array` `attr` argument and sets type for `seq`.
=> Fix bpy_prop_array.foreach_get/set arguments

src/fake_bpy_module/transformer/data_type_refiner.py, src/fake_bpy_module/transformer/default_value_filler.py, src/mods/common/analyzer/append/bpy.types.mod.rst, src/mods/common/analyzer/new/bpy.types.mod.rst, src/mods/common/analyzer/update/bpy.app.timers.mod.rst, src/mods/common/analyzer/update/bpy.types.mod.rst, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/various_data_type_transformed.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/default_value_filler_test/expect/basic.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/default_value_filler_test/expect/basic_transformed.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/default_value_filler_test/input/basic.rst
A continuation of the work towards resolving #161 that was started in #207—`typing.Sequence`, `typing.Iterable`, `typing.Iterator` and `typing.Callable` are all deprecated aliases to types of the same name in `collections.abc`.
I'm certainly not familiar with the codebase yet, so I'm submitting this now for checks and review even though it conflicts with #221.
=> Replace deprecated aliases to ABCs in collections.abc

src/mods/common/analyzer/append/bmesh.types.mod.rst, src/mods/common/analyzer/update/bmesh.types.mod.rst
- BMesh sequences were missing generic base class, so generic arguments and return values were not changing with subscription.
- Additionally BMesh sequences were being given methods they don't have, and `BMIter` was not being used as iterable return type.
- `BMLayerCollection`'s `get()` method now has a return type.
- Added `__getitem__()`, `__setitem__()` and `__delitem__()` to `BMVert`, `BMEdge`, `BMLoop` and `BMFace`.*
Fixes #179
*Presently these methods get/set `Any`—to fix this `BMLayerItem` needs to be made generic (trivial), but that generic type needs to come from `BMLayerCollection` which also needs to be made generic, which involves modding all of its methods and uses (non-trivial), and I don't think it's currently possible to bind that generic type to `BMLayerItem` (but it …
=> Fix BMesh typing (#179)

docs/generate_modules.md, src/gen_modfile/gen_bgl_modfile.py
1) add non-optional `-f` flag
2) replace bgl.c with bgl.cc as bgl.c is currently deprecated
=> fix building instructions

src/fake_bpy_module/generator/writers.py
Sometimes in union types there was duplicate element like `str | int | str` instead of `str | int`.
This PR now deduplicate union element and sort them to ensure reproducibility.
- Found this problem when working on #238
I added the function `make_union` to avoid code duplication.
=> Update: Sort and deduplicate union elements

src/mods/common/analyzer/new/bpy.types.mod.rst
- Fix #162 
`__get__` returns `bpy_prop_array[GenericType1]` which has the same behavior as currently.
`__set__` can receive any `Iterable[GenericType1]` like any other function arguments that have `bpy_prop_array` as expected type.
=> Update: Improve bpy_prop_array typing

src/mods/common/analyzer/append/bpy.types.mod.rst, src/mods/common/analyzer/new/bpy.types.mod.rst
`__getitem__()`, `__setitem__()` and `__delitem__()` for `bpy_prop_array` and `bpy_prop_collection` now all support passing a `slice` as a `key`, with overloads to change the return/input type to `tuple[GenericType]` when doing so.
=> Fix: slice support for bpy_prop_array and bpy_prop_collection

src/fake_bpy_module/transformer/data_type_refiner.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/various_data_type_transformed.xml
Fix the typing of handlers list.
The bracket for the callable arguments was not in the correct place.
=> Fix: typo in handlers callable typing

src/mods/common/analyzer/update/bpy.props.mod.rst
Fixes #246 
A couple of issues:
=> Fix typing of EnumProperty items parameter

src/mods/common/analyzer/update/bpy.types.mod.rst
The tool that automatically documents Blender's code is not able to distinguish the derived nodetrees from each other ([although it may be possible to add this functionality](https://projects.blender.org/blender/blender/issues/122737)), so `node_tree` attributes like that of `Material` were typed as a base `NodeTree` instead of the `ShaderNodeTree` actually returned. Additionally these attributes can return (and in some cases be set to) `None`.
=> Increase type specificity for node_tree attributes

src/mods/common/analyzer/append/bpy.types.mod.rst, src/mods/common/analyzer/new/bpy.types.mod.rst
`bpy_prop_collection` does not currently support assignment to slices or keys (only int indices); and while it does have a `__delitem__`, it just raises a `TypeError` "del bpy_prop_collection[key]: not supported".
`bpy_prop_array` does not support deleting slices.
=> Remove assignment to slices & keys and delitem from bpy_prop_collection

src/fake_bpy_module/transformer/data_type_refiner.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/various_data_type.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/various_data_type_transformed.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/input/various_data_type.rst
`boolean array of n items` was being typed as `list[bool]`, which was then incompatible with `tuple` default values, and was inconsistent with `int/float array of n items` which is typed as `Iterable` or `bpy_prop_array` depending on the application.
=> Array of boolean consistency with array of int/float

src/mods/common/analyzer/append/bpy.types.mod.rst, src/mods/common/analyzer/new/bpy.types.mod.rst
I keep making the mistake of writing a single-item tuple when I mean a homogenous tuple of undefined length, and nobody caught me on it.
Perhaps we should look into implementing tests for mod file changes?
Also the input for assignment does not have to a tuple, it can be any iterable.
=> Fix: get/set slice returns/accepts more than one item

docs/generate_modules.md, src/gen.py
The documentation and help text for `gen.py` still mentioned the removed `-d` option, while not mentioning the `-l` option.
=> Update help text/documentation for `gen.py`

src/mods/common/analyzer/append/mathutils.mod.rst
- Adds slicing support to `Color`, `Euler`, `Quaternion`, `Vector` and `Matrix`.
- Adds `__setitem__` for `Color`, `Euler` and `Matrix` which did not previously have them.
- Removes return value from `__setitem__` for `Quaternion` and `Vector`.
Resolves #274
=> Update: Add slice support to `mathutils` classes

src/mods/common/analyzer/append/bpy.types.mod.rst, src/mods/common/analyzer/append/mathutils.mod.rst, src/mods/common/analyzer/new/bpy.types.mod.rst
As discussed in #278 the non-`@overload`-decorated function definition that follows all `@overload`-decorated functions is the runtime implementation of the function, which should not be included in type stubs. This PR removes existing functions of this kind from the mod files.
=> Remove runtime definition for overloaded functions

src/mods/common/analyzer/append/bmesh.types.mod.rst, src/mods/common/analyzer/new/bpy.types.mod.rst, src/mods/common/analyzer/update/bmesh.types.mod.rst
A number of references to Blender classes not in the form `` :class:`bpy.example` `` existed in the mod files; this PR fixes that.
Of note: inline markup like this must be surrounded by "non-word characters", so `BMIter[BMVert]` requires an escaped space: ``:class:`BMIter`\ [:class:`BMVert`]``.
=> Cleanup: Ensure all references to bpy classes in mod files are class-ref

src/fake_bpy_module/transformer/self_rewriter.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/self_rewriter_test/expect/basic_transformed.xml
For Python version less than 3.11, type checkers (at least Pyright) will complain that `typing.Self` does not exist.
This PR imports `Self` from `typing_extensions` instead of `typing`.
=> Fix: Import Self from typing_extensions instead of typing

src/fake_bpy_module/transformer/self_rewriter.py
The fix of #270 caused a regression of #243 for self types that are optional.
The `option` attributes which can `accept none` or `never none` was not copied when rewriting to the self type.
To keep the info that the type is optional `attributes` is assigned to the new node.
=> Fix: Copy attributes when rewriting Self type for optional type

src/fake_bpy_module/generator/writers.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_code_writer_test/expect/children/module_1.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/generator_test_data/py_interface_writer_test/expect/children/module_1.pyi, tests/python/fake_bpy_module_test/fake_bpy_module_test/integration_test_data/integration_test/expect/multiple/module_1/__init__.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/integration_test_data/integration_test/expect/multiple/module_1/__init__.pyi
IntelliSense was not working in PyCharm because the child modules were not re-exported.
The imports should be of the form `from . import ops as ops` instead of `from . import ops` (c.f. https://typing.readthedocs.io/en/latest/reference/stubs.html#imports)
This issue was found by McPhail and reported on Discord.
Before | After
--- | ---
=> Fix: Re-export child modules

src/fake_bpy_module/transformer/data_type_refiner.py
It was failing with error because of the symbol "←" in one of the files (event_type_items.rst)
```
path \fake-bpy-module\src\gen_module-tmp\sphinx-in\bpy_types_enum_items\event_type_items.rst
Traceback (most recent call last):
File "\fake-bpy-module\src\gen.py", line 183, in <module>
main()
File "\fake-bpy-module\src\gen.py", line 179, in main
generate(rst_files, mod_files)
File "\fake-bpy-module\src\gen.py", line 13, in generate
documents = fbm.transform(documents, mod_files)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "\fake-bpy-module\src\fake_bpy_module\transformer\transformer.py", line 59, in transform
return t.transform(documents)
^^^^^^^^^^^^^^^^^^^^^^
File "\fake-bpy-module\src\fake_bpy_module\transformer\transformer.py", line 145, in transform
transformer.apply(**apply_params)
File …
```
=> Fix: parsing .rst on windows

src/fake_bpy_module/generator/writers.py, src/fake_bpy_module/transformer/data_type_refiner.py, src/fake_bpy_module/transformer/rna_enum_converter.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/integration_test_data/integration_test/expect/multiple/module_2/__init__.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/integration_test_data/integration_test/expect/multiple/module_2/__init__.pyi, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/description_dependency_transformed.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/various_data_type_transformed.xml, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/rna_enum_converter_test/expect/basic_transformed.xml
- Fix #318
Remove `from . import typing as typing` from `bpy/__init__.pyi` as it is not available in runtime.
=> Fix bpy.typing confused as std typing

docs/setup_visual_studio_code.md
* config for VSCode was incomplete 
* I added a config for `python.analysis` too, otherwise I could not get the config working 
* solution was provided here : https://stackoverflow.com/questions/73154451/configure-vscode-to-autocomplete-from-two-python-projects
=> Update vscode config

src/mods/common/analyzer/update/bpy.types.mod.rst
- Follow up on #340, @Andrej730 on discord noticed that `bpy_prop_collection_idprop.add()` return type could be improved from `typing.Any` to `_GenericType1`.
Add an update mod for the return type of  `bpy_prop_collection_idprop.add()`.
=> Use _GenericType1 for bpy_prop_collection_idprop.add() return type

src/fake_bpy_module/analyzer/nodes.py, src/fake_bpy_module/config.py, src/fake_bpy_module/generator/code_writer.py
Otherwise e.g. it was returning type[BaseClassNode] instead BaseClassNode instance resulting in errors like `argument missing for parameter "element_type"` or `Argument of type "type[BaseClassNode]" cannot be assigned to parameter "item" of type "Node" in function "append_child"
"type[type]" is incompatible with "type[Node]` in
https://github.com/nutti/fake-bpy-module/blob/23afc7b5b1ddca151a4e4cc04df2ebd1cfabaf7c/src/fake_bpy_module/transformer/bpy_module_tweaker.py#L195-L198
Also used `cls` instead of explicit name to avoid error `Expression of type "BaseClassNode" is incompatible with return type "Self@BaseClassNode"` near `create_template` `return`.
=> Fix typing issues

src/fake_bpy_module/transformer/data_type_refiner.py, tests/python/fake_bpy_module_test/fake_bpy_module_test/transformer_test_data/data_type_refiner_test/expect/option_rna_based_transformed.xml
As it's not true, e.g. `bpy.types.ID.library` can be None though it is readonly.
=> Fix: remove adding "never none" for "readonly" properties

docs/generate_modules.md, src/fake_bpy_module/generator/writers.py, src/gen_module.sh, tests/pylint_cycles.sh, tests/run_pre_tests.sh, tests/run_tests.sh, tools/pip_package/build_pip_package.sh
Added support for Python 3.11 as it probably makes sense to support as it is the current Blender main Python version (at least it's the main reason why I'm stuck on Python 3.11).
I believe, previously it was changed to Python 3.12 to support new `type` syntax when entire `fake-bpy-module` was moved to 3.12 but it was reverted and `type` syntax is supported either way since it's only used in '.pyi' files.
Ping @JonathanPlasse just in case.
=> Fix: Add Python 3.11 support for building and testing

src/mods/common/analyzer/append/bpy.utils.preview.mod.rst
This PR is fiixing issues in the example snippet:
```python
import bpy
from typing import assert_type
icons = bpy.utils.previews.new()
assert_type(icons["test"], bpy.types.ImagePreview)
assert_type(icons.get("test"), bpy.types.ImagePreview | None)
print(type(icons).__bases__)  # (<class 'dict'>,)
```
=> Fix: Use more specific dict type for ImagePreviewCollection #351

src/mods/common/analyzer/append/idprop.types.mod.rst
PR solves issues with an example below:
```python
import bpy
class MyPropertyGroup(bpy.types.PropertyGroup):
custom_1: bpy.props.FloatProperty(name="My Float")
custom_2: bpy.props.IntProperty(name="My Int")
bpy.utils.register_class(MyPropertyGroup)
bpy.types.Object.my_prop_grp = bpy.props.PointerProperty(type=MyPropertyGroup)
props: MyPropertyGroup = bpy.data.objects[0].my_prop_grp
props.custom_1 = 22.0
print(a:=list(props.keys()))
print(b:=list(props.values()))
print(c:=list(props.items()))
print(c:=list(props.items()))
```
Diff for fake bpy modules after PR:
```diff
diff --git a/build_files/idprop/types/__init__.pyi b/build_files/idprop/types/__init__.pyi
index 7ab9575..557abce 100644
--- a/build_files/idprop/types/__init__.pyi
+++ b/build_files/idprop/types/__init__.pyi
@@ -55,6 +55,6 …
```
=> Update: add `__iter__` for IDPropertyGroupView classes

tests/python/fake_bpy_module_test/run_tests.py, tests/python/import_module_test/run_tests.py
Fix Deprecation Warnings
Replaces deprecated `unittest.makeSuite()` with `unittest.defaultTestLoader.loadTestsFromTestCase()` in test files to resolve Python 3.13+ compatibility warnings which you can find in the [CI logs](https://github.com/nutti/fake-bpy-module/actions/runs/14770894059/job/41470653842#step:18:699):
```python
/home/runner/work/fake-bpy-module/fake-bpy-module/tests/python/fake_bpy_module_test/run_tests.py:72: DeprecationWarning: unittest.makeSuite() is deprecated and will be removed in Python 3.13. Please use unittest.TestLoader.loadTestsFromTestCase() instead.
```
=> Update test setup to use modern unittest API

src/fake_bpy_module/config.py, src/fake_bpy_module/utils.py, src/gen.py, src/mods/blender/2.79+/analyzer/update/bpy.props.mod.rst, src/mods/blender/3.3+/analyzer/update/bpy.props.mod.rst, src/mods/common/analyzer/update/bpy.props.mod.rst
Fixes #361
Originally I thought that `Any` would work for this, but then we would lose type information completely.
Implementing here an idea from @JonathanPlasse to use bounded generics to make callables kind of covariant instead of contravariant where we need it.
Was manually patching my `bpy.props` before and testing it for a week now - seems to cover all cases.
```python
from typing import Callable
class A:
pass
class B(A):
pass
def f(v: B) -> None:
pass
def g_bad(v: Callable[[A], None]) -> None:
pass
def g_good[T: A](v: Callable[[T], None]) -> None:
pass
g_bad(f)
g_good(f)
```
=> Update: Add generics to bpy.props callables to avoid false positives
